package:
  name: py3-flaky
  version: 3.7.0
  epoch: 0
  description: Plugin for nose or pytest that automatically reruns flaky tests
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/box/flaky
      tag: v${{package.version}}
      expected-commit: f449aaec02b776485939fa56135ca341f06c27bf

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: box/flaky
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - wolfi-base
        - py3-pytest
  pipeline:
    - runs: |
        pytest ./flaky_test.py
